FROM golang:alpine as builder   
                                
WORKDIR /go/src                 
COPY httpserver.go .            
                                
RUN go build -o httpd ./httpserver.go


From alpine:latest

WORKDIR /root/
COPY --from=builder /go/src/httpd .
RUN chmod +x /root/httpd

ENTRYPOINT ["/root/httpd"]
